const API='https://api.alquran.cloud/v1';
const state={surahs:[],current:null,edition:'en.asad',audio:null};
const $=s=>document.querySelector(s);
const loading=on=>$('#loading').classList.toggle('hidden',!on);
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
async function api(path){const r=await fetch(API+path);if(!r.ok)throw Error('Request failed');return (await r.json()).data}
async function init(){try{loading(true);state.surahs=await api('/surah');renderSurahs(state.surahs);loading(false)}catch(e){loading(false);$('#surahView').innerHTML='<div class="empty">Quran data could not be loaded. Please check your internet connection and try again.</div>'}}
function renderSurahs(list){$('#readerView').classList.add('hidden');$('#surahView').classList.remove('hidden');$('#surahView').innerHTML=list.length?`<div class="surah-grid">${list.map(s=>`<article class="surah-card" onclick="openSurah(${s.number})"><div class="num">${s.number}</div><div class="surah-info"><strong>${s.englishName}</strong><small>${s.revelationType} • ${s.numberOfAyahs} Ayahs</small></div><div class="arabic-name" dir="rtl">${s.name}</div></article>`).join('')}</div>`:'<div class="empty">No Surah found.</div>'}
async function openSurah(n){try{loading(true);const [ar,en]=await Promise.all([api(`/surah/${n}/quran-uthmani`),api(`/surah/${n}/${state.edition}`)]);state.current=ar;state.translation=en;renderReader(ar,en);loading(false);window.scrollTo({top:0,behavior:'smooth'})}catch(e){loading(false);toast('Unable to open Surah')}}
function renderReader(ar,en){$('#surahView').classList.add('hidden');$('#readerView').classList.remove('hidden');const s=ar;$('#readerView').innerHTML=`<div class="reader-head"><button class="back" onclick="backHome()">← Back</button><div class="reader-title"><h2>${s.name}</h2><p>${s.englishName} • ${s.revelationType} • ${s.numberOfAyahs} Ayahs</p></div></div><div class="controls"><button onclick="setFont(1)">A+ Arabic</button><button onclick="setFont(-1)">A− Arabic</button><button onclick="playAll()">▶ Listen</button><button onclick="stopAudio()">■ Stop</button></div><div id="ayahList">${s.ayahs.map((a,i)=>{const tr=en.ayahs[i];return `<article class="ayah" id="ayah-${a.numberInSurah}"><div class="ayah-top"><span>Ayah ${a.numberInSurah}</span><div class="ayah-actions"><button title="Bookmark" onclick="bookmark(${s.number},${a.numberInSurah},this)">☆</button><button title="Listen" onclick="playAyah(${a.number})">▶</button></div></div><div class="arabic">${a.text}</div><div class="translation">${tr.text}</div></article>`}).join('')}</div>`}
function backHome(){stopAudio();renderSurahs(state.surahs);document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelector('[data-view="surahs"]').classList.add('active')}
function setFont(delta){document.querySelectorAll('.arabic').forEach(x=>{const current=parseFloat(getComputedStyle(x).fontSize);x.style.fontSize=(current+delta)+'px'})}
function playAyah(number){stopAudio();const audio=new Audio(`https://cdn.islamic.network/quran/audio/128/ar.alafasy/${number}.mp3`);state.audio=audio;audio.play().catch(()=>toast('Audio could not start'));}
function playAll(){if(!state.current)return;stopAudio();let i=0;const next=()=>{if(i>=state.current.ayahs.length)return;const a=state.current.ayahs[i++];state.audio=new Audio(`https://cdn.islamic.network/quran/audio/128/ar.alafasy/${a.number}.mp3`);state.audio.onended=next;state.audio.play().catch(()=>toast('Audio could not start'))};next()}
function stopAudio(){if(state.audio){state.audio.pause();state.audio.currentTime=0;state.audio=null}}
function bookmark(surah,ayah,btn){const key=`quran-bookmark-${surah}-${ayah}`;if(localStorage.getItem(key)){localStorage.removeItem(key);btn.textContent='☆';toast('Bookmark removed')}else{localStorage.setItem(key,JSON.stringify({surah,ayah}));btn.textContent='★';toast('Ayah bookmarked')}}
function showBookmarks(){const items=Object.keys(localStorage).filter(k=>k.startsWith('quran-bookmark-')).map(k=>JSON.parse(localStorage.getItem(k)));if(!items.length){$('#surahView').innerHTML='<div class="empty">No bookmarks yet. Open a Surah and tap ☆ on an Ayah.</div>';return}$('#surahView').innerHTML=`<div class="surah-grid">${items.map(x=>`<article class="surah-card" onclick="openSurah(${x.surah}).then(()=>setTimeout(()=>document.getElementById('ayah-${x.ayah}')?.scrollIntoView({behavior:'smooth'}),400))"><div class="num">${x.surah}</div><div class="surah-info"><strong>Surah ${state.surahs.find(s=>s.number===x.surah)?.englishName||x.surah}</strong><small>Ayah ${x.ayah}</small></div><div>🔖</div></article>`).join('')}</div>`}
$('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){renderSurahs(state.surahs);return}renderSurahs(state.surahs.filter(s=>s.englishName.toLowerCase().includes(q)||s.name.includes(q)||String(s.number).includes(q)))});
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const v=btn.dataset.view;if(v==='surahs')renderSurahs(state.surahs);else if(v==='bookmarks')showBookmarks();else $('#surahView').innerHTML='<div class="empty">Juz navigation is coming next. The complete 114-Surah Quran reader is available now.</div>'}));
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('quran-dark',document.body.classList.contains('dark'))};
if(localStorage.getItem('quran-dark')==='true')document.body.classList.add('dark');
init();
